### ISSUE TITLE
Refactoring Issues

### ISSUE THREAD

**Issue by KonH** [KonH/UDBase#13]
- [x] Code Style
- [x] Protected instances
- [x] Sealed classes
- [x] Var names format (varName - local, VaName - public, _varName - private, VarName - const/static)
- [x] Better namespace usage?

**Comment by Leopotam** [comment]
suggest to use camelCase for args too, because they are just local vars at method scope. and no rules for constants ;)

**Comment by KonH** [comment]
Probably you're right,  that is more correctly. But once I saw the project with naming format like that and thought about what it allows to separate arguments and other entities.

**Comment by Leopotam** [comment]
read this article: https://rsdn.org/article/mag/200401/codestyle.XML - i use adapted version of this one. btw, microsoft uses very close code style, check this: https://github.com/Azure/azure-sdk-for-net

**Comment by KonH** [comment]
Thanks for the links, looks like what I looking for.
